### ISSUE TITLE
Typo in your website

### ISSUE THREAD

**Issue by wheezyturbo** [Theonlyhamstertoh/blog#3]
**Describe the bug**
Hey man I've been looking at your beautiful website, and I came across a typo

**To Reproduce**

1. Go to 'https://www.weibozhang.com/blog/now'
2. Scroll down to 'Working on Bluon AI'
4. You can see there is a typo there in the third list item

**Expected behavior**

**Screenshots**
![image](https://github.com/Theonlyhamstertoh/blog/assets/77047619/05d72fd0-e352-418e-a1b1-ca394d05d72f)

**Comment by Theonlyhamstertoh** [comment]
Hey, thank you so much! I have made some changes to the page! I really appreciate your feedback!
